### ISSUE TITLE
pre-publication checklist

### ISSUE THREAD

**Issue by grst** [grst/immune_deconvolution_benchmark#6]
- [x] check enumeration of supplementary figures and references hereto. 
- [x] upload on BioRXiv
- [x] submit

- [x] release `immundeconv` as conda package
- [x] release `immundeconv` package
- [x] re-pack cache files
- [x] make github repos public, transfer ownership of anaconda `r-immunedeconv`, make conda package public,
- [x] check installation instructions
- [x] check that pipeline is executable everywhere
- [x] check that pipeline is generic and allows adding new methods
- [x] release this repo, add data and cache to the release, update links in snakemake files. 
- [x] double-check supplementary information, re-compile and publish on gh-pages. 
- [x] update all titles and references to point to biorxiv
